stages:
- build
- deploy

melakukan-build-dan-package:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy-ke-heroku:
  stage: deploy
  image: openjdk:8-jdk
  variables:
    HEROKU_API_KEY: $HEROKU_API_KEY
  script:
    - apt-get update
    - apt-get install wget -y
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - heroku plugins:install heroku-cli-deploy
    - heroku deploy:jar target/*.jar --app $HEROKU_APP_NAME